### ISSUE TITLE
Color for exclusion-restriction variable in `plot_pred()` is coded wrong

### ISSUE THREAD

**Issue by hanneoberman** [amices/ggmice#125]
``` r
pred <- mice::quickpred(mice::nhanes)
pred[,1] <- -3
ggmice::plot_pred(pred)
```

![](https://i.imgur.com/axdPzYw.png)

<sup>Created on 2023-10-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by stefvanbuuren** [comment]
Hmm, interesting. Does 1 stand for "incomplete predictor" and -3 for "complete predictor"?

**Comment by hanneoberman** [comment]
There is currently no difference between complete and incomplete predictors. I have taken this from the [vignette](https://www.gerkovink.com/miceVignettes/Multi_level/Multi_level_data.html):
>    "In the predictor matrix, -2 denotes the class variable, a value 1 indicates a fixed effect and a value 2 indicates a random effect"

Instead of this from the [`mitml` package reference](https://cran.r-project.org/web/packages/mitml/mitml.pdf):
>    "1: target variables containing missing data
2: predictors with fixed effect on all targets (completely observed)
3: predictors with random effect on all targets (completely observed)
-1: grouping variable within which the imputation is run separately
-2: cluster indicator variable
0: variables not featured in the model"

The value `-3` would denote a new imputation model predictor type, implemented in the Heckman method in [`micemd`](https://github.com/cran/micemd/blob/master/R/mice.impute.2l.2stage.heckman.R).

**Comment by hanneoberman** [comment]
``` r
pred <- mice::quickpred(mice::nhanes)
pred[,1] <- -3
ggmice::plot_pred(pred)
```

![](https://i.imgur.com/goF04P6.png)

<sup>Created on 2023-10-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by stefvanbuuren** [comment]
Thanks. I wasn't aware of the -3 code. Perhaps we should start a code registry?

**Comment by hanneoberman** [comment]
Good idea! Maybe the [Wiki](https://github.com/amices/mice/wiki) feature on Github or a reference page on amices.org would be nice.

**Comment by stefvanbuuren** [comment]
I made a previous inventory. Perhaps we could that into a table of code by method

- Univariate imputation methods for two-level data use other codes than 0 and 1
- `2l.bin`, `2l.lmer`, `2l.norm`, `2l.pan`, `2lonly.mean`, `2lonly.norm` and `2lonly.pmm` use code `-2` to indicate the class variable
- `2l.bin`, `2l.lmer`, `2l.norm` and `2l.pan` use code 2 to indicate the random effects
- `2l.pan` uses codes 3 and 4 to add class means to codes 1 and 2 respectively
