### ISSUE TITLE
Add authors to `ggmice` functions

### ISSUE THREAD

**Issue by hanneoberman** [amices/ggmice#147]
See e.g. `ampute()` in `mice`

**Comment by hanneoberman** [comment]
Not necessary with git blame

**Comment by stefvanbuuren** [comment]
`git blame` tracks all code changes, which is precise in content and history. I think this is fine for reducing clutter in cases where one does not expect or invite contributions from others. 

I am unsure whether `git blame` is a suitable method for giving credit or stimulating contributions. The model in `mice` is to add separate "author" tags to documentation to acknowledge  (both in code and methodology) and features contributors at the package level "significant additions." In this way, it is a little easier for package users to see who contributed to a specific routine and contact and blame :-) those authors in case of problems.
