### ISSUE TITLE
Write some more tests

### ISSUE THREAD

**Issue by hanneoberman** [amices/ggmice#24]

**Comment by hanneoberman** [comment]
Current code coverage = 82%. Please feel free to add some use cases!

**Comment by hanneoberman** [comment]
For example, test whether `plot_pred()` works if `blocks` are defined

**Comment by gerkovink** [comment]
Will do

**Comment by hanneoberman** [comment]
Test if all functions work when the data has variable names that are used internally as well. For example, `.where` is used for the missingness indicator, but what if it's a variable name too?
