### ISSUE TITLE
Minor suggestion for plot_pattern second y-axis label

### ISSUE THREAD

**Issue by KLuijken** [amices/ggmice#57]
Hi Hanne,

The ggmice functions are super helpful!
One minor suggestion for the pattern plot came up. The second y-axis is titled "Pattern\n(number of missing entries)". Would it be more accurate to change this into "Pattern\n(number of missing variables)"?

Happy to hear your thoughts,
Kim

**Comment by hanneoberman** [comment]
Thanks both! I decided upon the following, but would appreciate your feedback:

``` r
ggmice::plot_pattern(mice::nhanes)
```

![](https://i.imgur.com/jkfiGkq.png)

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by KLuijken** [comment]
Agreed!
