### ISSUE TITLE
Plots malfunction when multiple columns contain the same string

### ISSUE THREAD

**Issue by kristenbhunter** [amices/ggmice#89]
First, I love this package!!  Thank you for developing it!

I have a small corner case that broke the plots.

I have two columns that contain the same string:
"foo"
"foo_bar"

Thanks to the line below, when trying to plot "foo", then "foo_bar" also gets put into vrb_x, and the plots don't work:
https://github.com/amices/ggmice/blob/main/R/ggmice.R#L39

**Comment by hanneoberman** [comment]
Thank you for bringing this to my attention. The issue should have been resolved now!

**Comment by kristenbhunter** [comment]
Thank you!!
